version: "3.9"
services:
  nginx:
    image: nginx:1.20
    ports:
      - "8080:80"
    volumes:
      - ./configs/nginx.conf:/etc/nginx/nginx.conf
      - ./www:/data/www
      - ./images:/data/images
      - ./php:/data/php
    depends_on:
      - "php-fpm"
  php-fpm:
    image: php:8-fpm
    volumes:
      - ./configs/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./php:/data/php
